// List kata kunci yang mau diblokir (bisa tambah)
// unused
export const BLOCKED_KEYWORDS = [
  'porn',
  'porno',
  'sex',
  'hentai',
  'xxx',
  'bokep',
  'jav',
  'adult',
  'nsfw',
  'casino',
  'judi',
  'slot',
  'zeus',
  'bet',
  'gambling',
  'toto',
  'agen sbobet',
  'zeus! your son has return!i bring the destruction of olympus',
  'Liveslot',
  'RTP Slot',
  'NoLimit Slot',
  'Situslot',
  'Slotgacor',
  'Pragmatikslot',
  'Casino online',
  'Togel',
  'Bonus slot',
  'CQ9',
  // Porn / Adult
  'porn',
  'porno',
  'sex',
  'hentai',
  'xxx',
  'bokep',
  'jav',
  'adult',
  'nsfw',
  'bdsm',
  'milf',
  'teen porn',
  'gay porn',
  'lesbian porn',
  'sexvideo',
  'adultvideo',
  'cams',
  'onlyfans',
  'lewd',
  'nude',
  'fetish',
  '18+',
  'xxnx',

  // Gambling / Betting / Casino / Slot
  'casino',
  'judi',
  'slot',
  'zeus',
  'bet',
  'gambling',
  'toto',
  'agen sbobet',
  'Liveslot',
  'RTP Slot',
  'NoLimit Slot',
  'Situslot',
  'Slotgacor',
  'Pragmatikslot',
  'Casino online',
  'Togel',
  'Bonus slot',
  'CQ9',

  // Extended gambling terms
  'gacor',
  'rtp',
  'rtp live',
  'jackpot',
  'maxwin',
  'slot88',
  'mega888',
  'playtech',
  'habanero',
  'pgsoft',
  'pg soft',
  'pragmatic',
  'spadegaming',
  'idn poker',
  'idnpoker',
  'poker online',
  'judi bola',
  'sbobet',
  'maxbet',
  'live casino',
  'slot online',
  'slot777',
  'olxslot',
  'indoslot',
  'vip slot',
  'togel online',
  'angka jitu',
  'parlay',
  'mix parlay',
  'slot resmi',
  'slot terpercaya',
  'deposit pulsa',
  'wd cepat',
  'slot deposit',
  'slot bonus',
  'betting online',
  'slot maxwin',
  'slot gampang menang',

  // Scam / phishing styled words (sering dipakai di domain judi)
  'vip88',
  'vip69',
  'vip99',
  '8899',
  '777',
  '188',
  'qq',
  'slot hoki',
  'bo slot',
  'bo togel',
  'agen slot',
  'situs judi',

  // Meme/phrase yang kamu masukin
  'zeus! your son has return!i bring the destruction of olympus',

  // Extra malicious/spammy marketing
  'daftar slot',
  'login slot',
  'daftar judi',
  'link alternatif',
  'link slot',
  'gampang jp',
  'mudah maxwin',
  'info rtp',
  'rtphariini',
  'rtp pragmatic',
  'rtp pg',
  'rtp live hari ini',

  // Adult site disguised keywords
  'camshow',
  'live sex',
  'sexchat',
  'naughty',
  'erotic',
  'premium porn',
  'porns',
  'pornhub',
  'redtube',
  'xvideos',
  'xnxx',
  // Porn
  'porn',
  'porno',
  'pornhub',
  'sex',
  'hentai',
  'xxx',
  'bokep',
  'jav',
  'adult',
  'nsfw',
  '18+',
  'lewd',
  'fetish',
  'erotic',
  'ecchi',
  'doujin',
  'uncensored',
  'bureau hentai',
  'rule34',
  'r34',
  'camgirl',
  'camsex',
  'OnlyFans',
  'ofans',
  'hotgirl',
  'sextape',
  'nudes',
  'sexchat',
  'bdsm',
  'anal',
  'fetish',
  'asphyx',
  'genshin r34',
  'AI hentai',
  'AI nude',

  // Casino / Gambling
  'casino',
  'judi',
  'slot',
  'bet',
  'gambling',
  'toto',
  'sbobet',
  'agensbobet',
  'rtp',
  'rtp slot',
  'slotgacor',
  'situslot',
  'pragmatik',
  'pragmatic',
  'nolimit',
  'cq9',
  'bonus slot',
  'jackpot',
  'megawin',
  'liveslot',
  'idnslot',
  'pgsoft',
  'betwin',
  'bet88',
  'zeus',
  'gates of olympus',
  'gacor',

  // Scam / Fraud
  'pinjaman online',
  'pinjol ilegal',
  'investasi bodong',
  'binary option',
  'binomo',
  'olymp trade',
  'robot trading',
  'trading palsu',
  'crypto scam',
  'giveaway palsu',
  'hadiah palsu',
  'dana cepat ilegal',
  'debt trap',

  // Malware / Darkweb
  'ransomware',
  'trojan',
  'keylogger',
  'botnet',
  'ddos',
  'rat tool',
  'keygen',
  'crack',
  'license crack',
  'hacktool',
  'bruteforce',
  'sql injection',
  'XSS',
  'stealer',
  'malware',
  'phishing',
  'spoofing',
  'carding',
  'fraud card',

  // General malicious
  'fake login',
  'web phish',
  'phish',
  'phisher',
  'bank phishing',
  'paypal scam',
  'fakebank',
  'fakeadmin',
  'fake support',
  'virus download',
  'spoof',
  'identity theft',
  'credential harvesting',
];

export function containsBlockedKeyword(url: string) {
  const lower = url.toLowerCase();
  return BLOCKED_KEYWORDS.some((kw) => lower.includes(kw));
}
