export const BLOCKED_KEYWORDS = [
  'porn',
  'porno',
  'pornhub',
  'sex',
  'hentai',
  'xxx',
  'bokep',
  'jav',
  'adult',
  'nsfw',
  '18+',
  'lewd',
  'fetish',
  'erotic',
  'ecchi',
  'doujin',
  'uncensored',
  'rule34',
  'r34',
  'onlyfans',
  'camgirl',
  'nudes',
  'bdsm',
  'sextape',

  'judi',
  'casino',
  'slot',
  'gacor',
  'rtp',
  'rtp slot',
  'sbobet',
  'toto',
  'slotgacor',
  'bonus slot',
  'nolimit',
  'pragmatic',
  'zeus',
  'gates of olympus',

  'binomo',
  'binary option',
  'investasi bodong',
  'pinjol ilegal',
  'scam',
  'phishing',
  'fake login',

  'malware',
  'trojan',
  'ransomware',
  'keylogger',
  'botnet',
  'rat',
  'ddos',
  'hacktool',
  'sql injection',
  'xss',
];

export const BLOCKED_REGEX = [
  /\b(porn|porno|sex|hentai|bokep|jav|xxx|nsfw|adult|onlyfans?)\b/i,
  /\b(judi|casino|slot|bet|rtp|sbobet|gacor|zeus)\b/i,
  /\b(binomo|bodong|binary\s*option|scam|phish|fake\s*login)\b/i,
  /\b(ransomware|trojan|malware|keylogger|botnet|rat|ddos)\b/i,
];

export const BLOCKED_WILDCARD = [
  /p[o0]rn/i,
  /pr[o0]n/i,
  /b[o0]kep/i,
  /s[e3]x/i,
  /j[uµ]di/i,
  /sl[o0]t/i,
  /sl[o0]tg[a4]c[o0]r/i,
  /c[a4]sino/i,
  /b[e3]t/i,
  /sc[a4]m/i,
  /ph[i1]sh/i,
  /malw[a4]re/i,
  /c[a4]sin[o0]/i,
];

export const SUSPICIOUS_TLDS = [
  'xyz',
  'top',
  'quest',
  'click',
  'link',
  'tokyo',
  'fit',
  'rest',
  'shop',
  'gq',
  'cf',
  'ml',
  'ga',
  'cam',
  'icu',
  'live',
  'fun',
];

export const DANGEROUS_DOMAIN_PATTERNS = [
  /\d{4,}/, // domain berisi angka terlalu banyak
  /(--|\.\.)/, // domain suspicious
  /(free|bonus|claim)/i, // spam words
];
